### ISSUE TITLE
Link to DeepSpeech benchmark patch is returning 404

### ISSUE THREAD

**Issue by JendrzejewskiP** [roscisz/TensorHive#124]
Link to DeepSpeech patch probably should be https://raw.githubusercontent.com/roscisz/TensorHive/master/examples/deepspeech/deepspeech_benchmarking.patch
instead of
https://raw.githubusercontent.com/roscisz/TensorHive/feature/deepspeech_example/examples/deepspeech/deepspeech_benchmarking.patch
![image](https://user-images.githubusercontent.com/45563278/49751540-e6694300-fcad-11e8-98ad-9c0c56477e2e.png)

**Comment by roscisz** [comment]
True, this is fixed in #7e2aa8332d51885b4d4c688a86129e192c91f0bc, along with some other fixes that you may find useful. It will be merged to master soon, with a bunch of distributed training benchmarks. Currently in branch feature/deepspeech_distributed_benchmarks.

**Comment by roscisz** [comment]
fixed in #127
