### ISSUE TITLE
Gather reservation statistics and generate summary

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#126]
This would be useful for all administrators who want to track which users are wasting computational power.
It should also allow the web app to travel in time when watching metric charts (how efficiently user's program was performing).

Initial thoughts:
- store data as JSON files (JSON is already supported by our nvidia-smi parser)
- sort these logs in some way (some directory structure)
- generate short summary (any maybe save to database?) after reservation ends
- delete data after some time (maybe 7 days?)
- allow disabling this feature via config file

Subtasks:
- [ ] Data structure (hierarchy, where to store) [split]
- [ ] Endpoint [split]
- [ ] Delete old data automatically

**Comment by roscisz** [comment]
fixed in #148
