### ISSUE TITLE
Implicit reusing deleted record's id - inconsistency problem

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#134]
## Steps to reproduce
0. Open web app
1. Make reservation
2. Wait until it ends
3. Check out files inside `~/.config/TensorHive/logs`. There should be `old_X.json` and `summary_X.json`
4. Delete aforementioned reservation from calendar
5. Make new reservation
6. See log file(s) during reservation time. There will be `old_X.json`, `summary_X.json` and `X.json` (but we should get `X+1.json` instead)
7. Notice that summary_X.json will be overwritten by the summary of newer `X.json` file.

The problem is that removing reservation record **allows for reusing old ids**.

Possible solutions:
- Ignore and allow for overriding summaries (inconsistency with reality)
- Disable reusing old ids
- Append some unique number to summary filename

**Comment by roscisz** [comment]
I vote disable reusing old ids if it is easy to do.

**Comment by micmarty** [comment]
We'll see :)

**Comment by micmarty** [comment]
Finally I solved this issue with such a clean workaround!
Keep in mind that it's only been used by `Reservation` model, but we may want to use it somewhere else though.
![image](https://user-images.githubusercontent.com/12485656/53196579-b2e55600-3618-11e9-811f-757ad7b7cecd.png)
