### ISSUE TITLE
Large icons instead of labels i sidebar

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#144]
Current:
![image](https://user-images.githubusercontent.com/12485656/52069403-f6e7bc80-257e-11e9-94c0-56fdba8f0558.png)

Collapse and replace with informative, big icons.:
![image](https://user-images.githubusercontent.com/12485656/52069416-fc450700-257e-11e9-8284-21039037d3dc.png)

**Comment by micmarty** [comment]
Current:
![image](https://user-images.githubusercontent.com/12485656/52069403-f6e7bc80-257e-11e9-94c0-56fdba8f0558.png)

Collapse and replace with informative, big icons.:
![image](https://user-images.githubusercontent.com/12485656/52069416-fc450700-257e-11e9-8284-21039037d3dc.png)

**Comment by roscisz** [comment]
fixed in #147
