### ISSUE TITLE
Mailbot: admin should get emails less frequently 

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#145]
### Introduction
Email-sending class should extend the current mechanism of sending messages every `X` minutes to a specific email address (implemented in #142 ).
As of now, admin will be cluttered with some huge amount of emails from our mailbot just because we don't treat him in any special way - which is wrong.

### Idea
Admin gets an email **just once** for a process with specific `pid`.

### Implementation ideas
The idea is that `time_of_last_email` should be redesigned so it stores more information, like `'pid'`, `'role'` (in case other admins are allowed to screw with users :smile:)

**Comment by roscisz** [comment]
done in #168
