### ISSUE TITLE
Threading error with sqlite when API server starts first

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#175]
Ideas:
- Delay start of `TaskSchedulingService` so it starts after API Server

It looks like only `terminate_scheduled` method causes this problem (and not `spawn_scheduled`)
![image](https://user-images.githubusercontent.com/12485656/57572551-3f373600-741c-11e9-913a-64981646bd92.png)

[EDIT] https://github.com/roscisz/TensorHive/pull/177
![image](https://user-images.githubusercontent.com/12485656/60741777-10949200-9f6b-11e9-9a78-6947e0adecea.png)

**Comment by micmarty** [comment]
not sure if fixed or not... @roscisz any objections or shall I close this one?

**Comment by roscisz** [comment]
haven't seen that for a long time, closing the issue
