### ISSUE TITLE
New watches should set `gpu_util`/`mem_util` param by default (not `fan_speed`)

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#180]
User expects to see most important info right away when clicking `Add watch`, not some funky `fan_speed`
![image](https://user-images.githubusercontent.com/12485656/58952234-7090f080-8793-11e9-87c4-e3794758373d.png)

![image](https://user-images.githubusercontent.com/12485656/58952195-53f4b880-8793-11e9-863d-6f6a61ca3730.png)

**Comment by roscisz** [comment]
seems fixed
