### ISSUE TITLE
Please add citation template

### ISSUE THREAD

**Issue by piojanu** [roscisz/TensorHive#183]
Hi!

Your repo misses bibtex citation. How am I supposed to cite this amazing tool? Any self-respecting tool or framework have one. Here you can see an example off the top of my head: https://github.com/piojanu/humblerl/blob/master/README.md.

Thanks for your work, much appreciated!

P.S. I'd like to thank especially Karol Draszawka. He is amazing guy and I hope he will give me A for my extraordinary thesis. Peace :v:

**Comment by micmarty** [comment]
Thanks for your feedback @piojanu :heart:, we're so happy to hear that! We also hope you'll get A grade for your thesis :muscle: 

We'll have new a `README` file for newcomers ([preview link](https://github.com/roscisz/TensorHive/tree/feature/updated_readme#tensorhive)) in the next few days, we will definetely include BibTex.

@roscisz leave your thoughts on this, so I can put it into my existing PR.
```
@misc{tensorhive,
  author = {Michal Martyniak and Filip Schodowski and Pawel Rosciszewski},
  title = {TesnorHive - open source SSH-based system for GPU reservation and monitoring in multi-node environment},
  year = {2019},
  publisher = {GitHub},
  journal = {GitHub repository},
  url = {https://github.com/roscisz/TensorHive}
}
```

**Comment by roscisz** [comment]
We can leave it like this (after changing TesnorHive to TensorHive) for now, but we will be working towards publishing a paper introducing TensorHive, and that will be the ultimate citation.

**Comment by micmarty** [comment]
Typo fixed
