### ISSUE TITLE
Update schedule and calendar periodically (or trigger by some event)

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#188]
Person 1 has calendar in state A.
Person 2 makes reservation (or whatever) - state B

Person 1 won't see new state B without refreshing the page.

Not sure if reloading schedule + calendar should occur on some action/event or just managed by timer.
Maybe give users a button for manual refreshing instead?

@filschod @roscisz ?

**Comment by filschod** [comment]
fixed in 20a48d7
