### ISSUE TITLE
Upgrade reservation schedule component

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#190]
* Group GPUs by hostname (expandable list)
![image](https://user-images.githubusercontent.com/12485656/61134704-7a0f2600-a4c0-11e9-9729-ee8d7a6f313c.png)
* Allow selecting hostname (selects all its GPUs)
* Bar with days/hours must be always visible when scrolling to bottom
![image](https://user-images.githubusercontent.com/12485656/61134767-9c08a880-a4c0-11e9-8ce7-a95d4a628ff4.png)
* **Remember state** of checkboxes when switching dashboards, logging out
* When making new reservation **automatically select all GPUs that were selected in schedule**
![image](https://user-images.githubusercontent.com/12485656/61134912-e68a2500-a4c0-11e9-9da4-51ef22a26955.png)
* There are problems with table cells (schedule) - misalignments in comparison with calendar

**Comment by roscisz** [comment]
1, 2, 3 done,
4,5 opened in new issues,
6 probably fixed
