### ISSUE TITLE
Select all resources automatically when all checkboxes are empty (inconsistent behavior)

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#197]
### Subject of the issue
Inconsistent state - checkboxes are unselected, but all columns are visible

### Steps to reproduce
1. Open main page
2. **(inconsistency) None of checkboxes are selected, but all columns are visible**
3. Select some GPUs
4. Everything's good
3. Unselect these checkboxes
4. **(inconsistency) There are no columns selected**

![image](https://user-images.githubusercontent.com/12485656/61218159-a968a180-a711-11e9-8bdc-0eb24c8e10d4.png)

### Expected behaviour
(Only my suggestion - needs discussion with @roscisz @filschod )
1. Start with all checkboxes being selected
2. If user wants only some columns, he must deselect "Select all" checkbox, then select interesting ones manually

### Actual behaviour
1. Opening view
2. All checkboxes are deselected, but calendar shows all columns

**Comment by filschod** [comment]
fixed in e43bb7b
