### ISSUE TITLE
Task nursery: log preview enhancements

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#201]
- [ ] Add some kind of "refresh" button to fetch new log file contents
- [ ] Alternatively do it automatically every X seconds (pooling API endpoint)
- [ ] I think this should be only allowed when using `tail mode` (need to implement such checkbox, backend already has that feature)

**Comment by micmarty** [comment]
easy to implement

**Comment by roscisz** [comment]
fixed in #245
