### ISSUE TITLE
flake8 fails on branch develop

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#219]
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'
tensorhive/core/violation_handlers/MessageSendingBehaviour.py:31:10: W605 invalid escape sequence '\e'

**Comment by micmarty** [comment]
should be fixed in: 278a9aca508633873535c795f94ff600f50a0665 and cb0f35f9bb7a99d988182ada54176a3b6bb2ca59
