### ISSUE TITLE
Task queue and scheduler for non-reserved time

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#267]
Implement a queue of tasks which will be scheduled automatically when there are no reservations.

**Comment by roscisz** [comment]
Such a task queue will require a (at least simple) scheduler. The scheduler should support specifying hardware requirements. However, the scheduler will only have access to device attributes provided by the [REST API](https://github.com/roscisz/TensorHive/blob/22650f2cb7b31f25306874543ce8722d8193f7b8/tensorhive/api/api_specification.yml#L1412), which are currently limited to CPU/GPU, GPU index, GPU name, total memory, available memory. This might be enough to start ("for this task I need a GPU with at least 12GB V-RAM"), but we should gather more detailed attributes in the future. For example, CUDA driver version, system-wide library versions. Any other suggestions?

**Comment by infokiller** [comment]
I think the attributes you mentioned are sufficient. Regarding system-wide library versions, that can be worked around by using containers like Docker. The CUDA driver, on the other hand, can't be changed in a container, at least according to this diagram (from https://github.com/NVIDIA/nvidia-docker):

![image](https://user-images.githubusercontent.com/10516814/95810010-b0b59b00-0d18-11eb-9bc4-a35e783bac6e.png)

**Comment by roscisz** [comment]
basic version implemented in #337
