### ISSUE TITLE
Ability to add resources to restriction by hostname

### ISSUE THREAD

**Issue by jszemplinski** [roscisz/TensorHive#295]
User should be able to add resources to restriction by specifying a hostname which is common among these resources.

TODO:

- [x] DB - Table for resources should include their hostnames
- [x] Backend - New endpoint for adding resources by hostname
- [x] Frontend - View with adding resources to restriction should be extended to allow for looking up resources by hostname

**Comment by roscisz** [comment]
fixed in #307
