### ISSUE TITLE
Reservation permissions flaw - security bug?

### ISSUE THREAD

**Issue by jachoo** [roscisz/TensorHive#303]
### Reservation permissions flaw - security bug?

I've found a flaw in permissions system.

As this is probably a security bug (rather not critical, but needs checking), please contact me privately for details.

_GitHub doesn't allow to create confidential issues in public repositories :( Shame on you, GitHub!_

**Comment by jszemplinski** [comment]
@jachoo You didn't leave any contact info and I can't find any in your profile, so could you please send me the details of the issue to my email: jszemplinski98 at gmail.com? Thanks.
