### ISSUE TITLE
Integration tests should consider user permissions

### ISSUE THREAD

**Issue by jszemplinski** [roscisz/TensorHive#305]
Right now the integration tests are simply ignoring the @admin_required decorator when calling endpoints. This makes it unable to detect cases when user has access to an endpoint he/she shouldn't have access to.

The tests should allow to specify whether to execute a testcase as an admin or as an user and in case of insufficient privileges, expect an Unauthorized response.

**Comment by roscisz** [comment]
fixed in #296
