### ISSUE TITLE
Prohibit modification of past reservations

### ISSUE THREAD

**Issue by jachoo** [roscisz/TensorHive#306]
### Prohibit modification of past reservations

It should be not possible to modify reservations that are already finished. Moreover, modification of active reservations should be restricted to certain actions.

Now, users can easily change their reservations, including removing/adding them in the past, so that it's hard to see it they comply with the reservation rules.

### Your environment

* TensorHive v0.3.3 API v0.3

### Expected behaviour

My proposition:
* If reservation is in future, allow everything
* If reservation is active, disallow changing its start time
* If reservation is finished, disallow everything
* Optionally, name of the reservation could be also locked after reservation started

### Actual behaviour

I can change the past! ;)

**Comment by roscisz** [comment]
fixed in #296
