### ISSUE TITLE
Cannot cancel reservation

### ISSUE THREAD

**Issue by cygerts** [roscisz/TensorHive#324]
Sometimes when I try to cancel my reservation I got an error "Unpriviliged" (see the screenshot). 

![Zrzut ekranu z 2021-01-25 17-13-14](https://user-images.githubusercontent.com/8560577/105732438-ba15ec80-5f30-11eb-8d59-f8066e59380d.png)

**Comment by roscisz** [comment]
@cygerts Since TH 0.3.5, it is forbidden to cancel reservations that have already started. This is in order to avoid careless reservations ;) Could this be the case?

**Comment by cygerts** [comment]
Exactly;)

**Comment by roscisz** [comment]
So for now "It's not a bug, it's a a feature" :).

Thank you for the report though.
