### ISSUE TITLE
Unprivileged when canceling ongoing reservation

### ISSUE THREAD

**Issue by tymons** [roscisz/TensorHive#358]
### Subject of the issue
Cannot cancel ongoing reservation

### Your environment
List relevant info:
* Web app

### Steps to reproduce
Reserve some GPU and try to cancel it

![obraz](https://user-images.githubusercontent.com/21088812/151310141-fc1a36e7-a35e-4ab4-9c13-56eca13d7a78.png)

### Expected behaviour
Reservation should be deleted

### Actual behaviour
Reservation is not deleted

**Comment by roscisz** [comment]
Thanks for being an active user!

This is actually a feature :) Suggested here: #306 
It seemed to me a valid proposition to avoid cancelling ongoing reservations, so that the users take responsibility for their reservations.

Do you see it otherwise, maybe some use cases where this doesn't make sense?

**Comment by tymons** [comment]
Now it makes much more sense. Nevertheless I could image situation where estimated resource consumption was lower than expected and one could released unused gpu for other users' tasks. Second scenario would be just silly mistake:)

Keep up the good work!

**Comment by roscisz** [comment]
For such cases we decided to allow modifying (updating) the end time of the reservation to no earlier than now. Could you kindly verify that a) this is indeed the solution for your case, b) it works in your environment? 

Thanks!

**Comment by tymons** [comment]
Yes it worked as it was the first thing which I decided to do. Issue cloud be closed in my opinion.

Best,
TC
