### ISSUE TITLE
Memory leak in javascriptrrd

### ISSUE THREAD

**Issue by roscisz** [roscisz/TensorHive#7]
Periodic chart refreshing causes browser to consume infinite memory.

The following change fixes the leak, but also turns off the charts:

`--- a/tensorhive/static/javascriptrrd.wlibs.js
+++ b/tensorhive/static/javascriptrrd.wlibs.js
@@ -3098,6 +3098,7 @@ function RRDFileSum(file_list,sumfile_options) {
  *    
 /* Internal helper function */
 function rrdFlotAsyncCallback(bf,obj) {
+  return 1;^M
   var i_rrd_data=undefined;
   if (bf.getLength()<1) {
     //alert("File "+obj.url+" is empty (possibly loading failed)!");
`

**Comment by micmarty** [comment]
We don't use this library anymore.
