### ISSUE TITLE
Uncaught edge case (nvidia-smi pmon on TITAN X)

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#76]
TensorHive does not break, fortunately... but look at **pid, command, owner**.
We need to find out why nvidia-smi gives '-' on that GPU...
```json
# Infrastructure dict excerpt
 "GPU-1547ce67-0cc9-9a71-44d2-74855381bab3": {
                "processes": [
                    {
                        "command": "-",
                        "pid": "-",
                        "owner": null
                    }
                ],
                "index": 1,
                "name": "GeForce GTX TITAN X",
}

```

```
$ nvidia-smi -L
GPU 0: GeForce GTX 780 Ti (UUID: GPU-83012632-91d5-80cd-8b08-78e96c31195b)
GPU 1: GeForce GTX TITAN X (UUID: GPU-1547ce67-0cc9-9a71-44d2-74855381bab3)

$ nvidia-smi pmon --id 'GPU-83012632-91d5-80cd-8b08-78e96c31195b' # GTX 780 - this is handled properly
Not supported on the device(s)
Failed to process command line 

$ nvidia-smi pmon --id 'GPU-1547ce67-0cc9-9a71-44d2-74855381bab3' # GTX TITAN X - where that '-' come from???
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    1          -     -     -     -     -     -   -              
    1          -     -     -     -     -     -   -              
    1          -     -     -     -     -     -   -              
```

**Comment by rickyim** [comment]
Is this problem resolved? Cuz I came across the same bug. Driver version 411.31

**Comment by micmarty** [comment]
@rickyim I'm so sorry for not getting notification about your comment :cry: ! As of now we used to ignore this behavior, but now we're working on this right in order to preserve consistency across all monitored nodes. Relying on 

#### Current TensorHive behavior
One node shows explicitly that it's free (because of `-` in nvidia-smi's output):
![image](https://user-images.githubusercontent.com/12485656/61853370-0dcaf400-aebc-11e9-86c9-282e8d85be27.png)

Other node does not show unused cards at all:
![image](https://user-images.githubusercontent.com/12485656/61853530-67cbb980-aebc-11e9-9ee7-094b2e97971d.png)

**Comment by micmarty** [comment]
not resolved, but does not make any problems
