### ISSUE TITLE
Don't allow making reservation with no resources chosen.

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#78]
## Problem
User is able to click "Reserve" button when no resources were selected, without any warning.
He won't see the reservation in calendar (of course) but it may be frustrating for him, only because he forgot to select a checkbox.

# Image
![image](https://user-images.githubusercontent.com/12485656/45094821-b6ddf400-b11c-11e8-87f9-d5cb4d6041a6.png)

## Proposed solution
When no checkbox is selected:
- Show warning message
or
- Disable "Reserve" button

**Comment by roscisz** [comment]
fixed in #87
