### ISSUE TITLE
Customizable reservation rules mechanism

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#81]
Feature description
--------------------
It would be very useful for **admins** to change rules of creating reservations by users **on the fly**

First step: store them in `.ini` config file (requires restarting TensorHive)
In the future: store in database (fully dynamic, on the fly, accessible from the browser)

example:
```
foobar_user: reservation disabled
all_users: reservation max_duration 24h
all_users: reservation must_start_after 16:00
all_users: reservation must_end_before 10:00
```

Existing solutions
-----------------
I started to dig down the topic and I found this: https://github.com/venmo/business-rules
We could store the rules in our database (haven't tried that yet)

Summary
---------
It may get time consuming to implement, especially for the web app, but I think this feature is a must.

**Comment by roscisz** [comment]
Well, actually it is done in #262, #291 and #307
