### ISSUE TITLE
API configuration does not affect Vue web app

### ISSUE THREAD

**Issue by micmarty** [roscisz/TensorHive#85]
## Problem description

Although TensorHive is configured from `.ini` files, web app is not.

If user would change API `host`, `port` or `url_prefix` it would affect TenosrHive only.
Vue app would still rely on the hardcoded URL: `0.0.0.0:1111/api/0.2`
![image](https://user-images.githubusercontent.com/12485656/45556582-e1762e00-b83b-11e8-9c14-a68bf92f0447.png)
![image](https://user-images.githubusercontent.com/12485656/45556616-fc48a280-b83b-11e8-9f32-18ddb37e3731.png)

## Problematic code
![image](https://user-images.githubusercontent.com/12485656/45556478-ac69db80-b83b-11e8-82c6-4aeae675df9d.png)

## Proposed solution
1. Read and parse `main_config.ini`
2. Inject variables directly from python server (`AppServer.py`) via routes
Need to dig the topic down...

**Comment by roscisz** [comment]
fixed in #92

**Comment by roscisz** [comment]
fixed in #105
